/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OutdoorDoctorRouteImport } from './routes/outdoor-doctor'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DepartmentsIndexRouteImport } from './routes/departments/index'
import { Route as DepartmentsIdRouteImport } from './routes/departments/$id'
import { Route as DoctorsIndexRouteImport } from './routes/doctors/index'
import { Route as DoctorsSlugRouteImport } from './routes/doctors/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesIdRouteImport } from './routes/services/$id'
import { Route as ServicesBalurghatRouteImport } from './routes/services/balurghat'
import { Route as ServicesGangarampurRouteImport } from './routes/services/gangarampur'
import { Route as ServicesKolkataRouteImport } from './routes/services/kolkata'
import { Route as ServicesMaldaRouteImport } from './routes/services/malda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OutdoorDoctorRoute = OutdoorDoctorRouteImport.update({
  id: '/outdoor-doctor',
  path: '/outdoor-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdRoute = DepartmentsIdRouteImport.update({
  id: '/departments/$id',
  path: '/departments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBalurghatRoute = ServicesBalurghatRouteImport.update({
  id: '/services/balurghat',
  path: '/services/balurghat',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGangarampurRoute = ServicesGangarampurRouteImport.update({
  id: '/services/gangarampur',
  path: '/services/gangarampur',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesKolkataRoute = ServicesKolkataRouteImport.update({
  id: '/services/kolkata',
  path: '/services/kolkata',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMaldaRoute = ServicesMaldaRouteImport.update({
  id: '/services/malda',
  path: '/services/malda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/gallery': typeof GalleryRoute
  '/outdoor-doctor': typeof OutdoorDoctorRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/balurghat': typeof ServicesBalurghatRoute
  '/services/gangarampur': typeof ServicesGangarampurRoute
  '/services/kolkata': typeof ServicesKolkataRoute
  '/services/malda': typeof ServicesMaldaRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/gallery': typeof GalleryRoute
  '/outdoor-doctor': typeof OutdoorDoctorRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/balurghat': typeof ServicesBalurghatRoute
  '/services/gangarampur': typeof ServicesGangarampurRoute
  '/services/kolkata': typeof ServicesKolkataRoute
  '/services/malda': typeof ServicesMaldaRoute
  '/departments': typeof DepartmentsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/gallery': typeof GalleryRoute
  '/outdoor-doctor': typeof OutdoorDoctorRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/services/$id': typeof ServicesIdRoute
  '/services/balurghat': typeof ServicesBalurghatRoute
  '/services/gangarampur': typeof ServicesGangarampurRoute
  '/services/kolkata': typeof ServicesKolkataRoute
  '/services/malda': typeof ServicesMaldaRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointments'
    | '/career'
    | '/contact'
    | '/cookies'
    | '/gallery'
    | '/outdoor-doctor'
    | '/privacy'
    | '/terms'
    | '/departments/$id'
    | '/doctors/$slug'
    | '/services/$id'
    | '/services/balurghat'
    | '/services/gangarampur'
    | '/services/kolkata'
    | '/services/malda'
    | '/departments/'
    | '/doctors/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointments'
    | '/career'
    | '/contact'
    | '/cookies'
    | '/gallery'
    | '/outdoor-doctor'
    | '/privacy'
    | '/terms'
    | '/departments/$id'
    | '/doctors/$slug'
    | '/services/$id'
    | '/services/balurghat'
    | '/services/gangarampur'
    | '/services/kolkata'
    | '/services/malda'
    | '/departments'
    | '/doctors'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointments'
    | '/career'
    | '/contact'
    | '/cookies'
    | '/gallery'
    | '/outdoor-doctor'
    | '/privacy'
    | '/terms'
    | '/departments/$id'
    | '/doctors/$slug'
    | '/services/$id'
    | '/services/balurghat'
    | '/services/gangarampur'
    | '/services/kolkata'
    | '/services/malda'
    | '/departments/'
    | '/doctors/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  GalleryRoute: typeof GalleryRoute
  OutdoorDoctorRoute: typeof OutdoorDoctorRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  DepartmentsIdRoute: typeof DepartmentsIdRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  ServicesIdRoute: typeof ServicesIdRoute
  ServicesBalurghatRoute: typeof ServicesBalurghatRoute
  ServicesGangarampurRoute: typeof ServicesGangarampurRoute
  ServicesKolkataRoute: typeof ServicesKolkataRoute
  ServicesMaldaRoute: typeof ServicesMaldaRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outdoor-doctor': {
      id: '/outdoor-doctor'
      path: '/outdoor-doctor'
      fullPath: '/outdoor-doctor'
      preLoaderRoute: typeof OutdoorDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id': {
      id: '/departments/$id'
      path: '/departments/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof DepartmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/balurghat': {
      id: '/services/balurghat'
      path: '/services/balurghat'
      fullPath: '/services/balurghat'
      preLoaderRoute: typeof ServicesBalurghatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/gangarampur': {
      id: '/services/gangarampur'
      path: '/services/gangarampur'
      fullPath: '/services/gangarampur'
      preLoaderRoute: typeof ServicesGangarampurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/kolkata': {
      id: '/services/kolkata'
      path: '/services/kolkata'
      fullPath: '/services/kolkata'
      preLoaderRoute: typeof ServicesKolkataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/malda': {
      id: '/services/malda'
      path: '/services/malda'
      fullPath: '/services/malda'
      preLoaderRoute: typeof ServicesMaldaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  GalleryRoute: GalleryRoute,
  OutdoorDoctorRoute: OutdoorDoctorRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  DepartmentsIdRoute: DepartmentsIdRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  ServicesIdRoute: ServicesIdRoute,
  ServicesBalurghatRoute: ServicesBalurghatRoute,
  ServicesGangarampurRoute: ServicesGangarampurRoute,
  ServicesKolkataRoute: ServicesKolkataRoute,
  ServicesMaldaRoute: ServicesMaldaRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
